[tool.poetry]
name = "course-project"
version = "0.1.0"
description = "Курсовая работа по Python Сервис управления рассылками"
authors = ["Алексей <alekseyfilippov9392@gmail.com>"]
readme = "README.md"
packages = [{ include = "course_project", from = "src" }]

[tool.poetry.dependencies]
python = "^3.13"
django = "^6.0.2"


[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
isort = "^7.0.0"
flake8 = "^7.3.0"
mypy = "^1.19.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88



[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
